spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_hub?serverTimeZone=Asia/Seoul
    username: root
    password: evan

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never