spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json