spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/content_hub
    username: postgres
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    hibernate:
      ddl-auto: none